spring:
  cloud:
    gateway:
      routes:
        - id: medilabo_patient
          uri: http://medilabo-patient:8081
          predicates:
            - Path=/patients/**
        - id: medilabo_notes
          uri: http://medilabo-notes:8083
          predicates:
            - Path=/notes/**
        - id: medilabo_risk
          uri: http://medilabo-risk:8084
          predicates:
            - Path=/risk/**